syntax = "proto3";

service Req {
    rpc distributeBrokerage (distributeBrokerageReq) returns (distributeBrokerageRes) {}
    rpc updateSTV (updateSTVReq) returns (updateSTVRes) {}
}

message distributeBrokerageReq {
    string refereeId = 1;
    string orderId = 2;
    string currencyId = 3;
    string amount = 4;
    string exchange = 5;
}

message distributeBrokerageRes {
    bool status = 1;
}

message updateSTVReq {
    string userId = 1;
    string exchange = 2;
    string amount = 3;
    string currencyId = 4;
}

message updateSTVRes {
    bool status = 1;
}